version: "3.5"

services:
  app:
    build: "."
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - "/Users/ty/server/video_server/configs:/configs"
      # 挂载证书
      - "/Users/ty/server/Twitta/certs:/etc/ssl/certs/"
    networks:
      - app_net

networks:
  app_net:
    external: true