version: "1.0"
debug_mode: "debug"
addr: "0.0.0.0:8081"
name: "video_server"

mysql:
  addr: "127.0.0.1:3306"
  user: "root"
  password: "123"
  db: "video_server"
  casbin_db: "casbin"
  charset: "utf8mb4"
redis:
  addr: "127.0.0.1:6379"
  user: ""
  password: ""
minio:
  end_point: "127.0.0.1:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  user_ssl: false
delete_cron_time: "0 0 3 * * ?"
jwt:
  key: "my_secret_key"
  duration: 2678400
md5:
  secret: "ty"
log:
  runtime_path: "/logs/"
  track_path: "/err_logs/"
gRpc:
  user_service:
    addrSlice:
      "127.0.0.1:8080"