version: 1.0
params:
  service_name: video_server
  service_addr: 0.0.0.0
  service_port: 8081
connections:
  mysql:
    video_server:
      host: localhost
      user: root
      password: 123
      port: 3306
      db: video_server
      casbin_db: casbin
      charset: utf8mb4
  redis:
    video_server:
      host: localhost
      port: 6379
      user: ""
      password: ""
scheduler:
  delete_video:
    cron_time: 0 0 3 * * ?
minio:
  end_point: 127.0.0.1:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  user_ssl: false
jwt:
  key: my_secret_key
  duration: 2678400
md5:
  secret: ty
log:
  runtime:
    path: /logs/
  track:
    path: /err_logs/

gRpc:
  user_service:
    addrSlice:
      127.0.0.1:8080